language: node_js
node_js:
    - v6
before_script:
    - 'npm install -g bower gulp-cli'
    - 'npm install'
    - 'bower install'
after_script:
    - 'gulp'
    - "npm install -g coveralls && cat ./coverage/lcov.info | coveralls"
